name: Lint and Testing

on: push

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 20

      - run: npm install -g yarn
        shell: sh

      - run: yarn install
        shell: sh

      - run: yarn lint
        shell: sh

      - run: yarn test:unit
        shell: sh
